#include <stdio.h>

void cxta_test_math(void);
void cxta_test_smoothing(void);
void cxta_test_range(void);
void cxta_test_rolling(void);
void cxta_test_cross(void);
void cxta_test_candles(void);
void cxta_test_patterns(void);
void cxta_test_fib(void);
void cxta_test_wedge(void);
void cxta_test_tf(void);
void cxta_test_bar(void);
void cxta_test_window(void);
void cxta_test_args(void);
void cxta_test_pivot(void);
void cxta_test_pivot_points(void);
void cxta_test_bos(void);
void cxta_test_fvg(void);
void cxta_test_order_block(void);
void cxta_test_liquidity(void);
void cxta_test_sfp(void);
void cxta_test_indicator_vwap(void);
void cxta_test_structure_wedge(void);
void cxta_test_sma(void);
void cxta_test_ema(void);
void cxta_test_atr(void);
void cxta_test_rsi(void);
void cxta_test_macd(void);
void cxta_test_bollinger(void);
void cxta_test_adx(void);
void cxta_test_supertrend(void);
void cxta_test_donchian(void);
void cxta_test_keltner(void);
void cxta_test_price_channel(void);
void cxta_test_volume_sma(void);
void cxta_test_wma(void);
void cxta_test_dema(void);
void cxta_test_tema(void);
void cxta_test_hma(void);
void cxta_test_roc(void);
void cxta_test_linreg(void);
void cxta_test_stddev(void);
void cxta_test_hvol(void);
void cxta_test_rvol(void);
void cxta_test_truerange(void);
void cxta_test_typical(void);
void cxta_test_median(void);
void cxta_test_wclose(void);
void cxta_test_obv(void);
void cxta_test_zscore(void);
void cxta_test_extrema(void);
void cxta_test_ao(void);
void cxta_test_bop(void);
void cxta_test_eom(void);
void cxta_test_volume_ema(void);
void cxta_test_rma(void);
void cxta_test_aroon(void);
void cxta_test_williamsr(void);
void cxta_test_cci(void);
void cxta_test_mfi(void);
void cxta_test_cmf(void);
void cxta_test_chaikin(void);
void cxta_test_dpo(void);
void cxta_test_cmo(void);
void cxta_test_ppo(void);
void cxta_test_pvo(void);
void cxta_test_trix(void);
void cxta_test_tsi(void);
void cxta_test_kst(void);
void cxta_test_mass_index(void);
void cxta_test_efi(void);
void cxta_test_nvi(void);
void cxta_test_stochastic(void);
void cxta_test_stochrsi(void);
void cxta_test_mama(void);
void cxta_test_kama(void);
void cxta_test_frama(void);
void cxta_test_vidya(void);
void cxta_test_fisher(void);
void cxta_test_connors_rsi(void);
void cxta_test_coppock(void);
void cxta_test_schaff(void);
void cxta_test_choppiness(void);
void cxta_test_ulcer(void);
void cxta_test_rvi(void);
void cxta_test_vwap(void);
void cxta_test_vortex(void);
void cxta_test_dominant_cycle(void);
void cxta_test_ichimoku(void);
void cxta_test_psar(void);
void cxta_test_ttm_squeeze(void);
void cxta_test_trendline(void);
void cxta_test_volume_profile(void);
void cxta_test_zigzag(void);
void cxta_test_divergence(void);
void cxta_test_anchored_vwap(void);
void cxta_test_descriptor(void);

int main(void) {
    cxta_test_math();
    cxta_test_smoothing();
    cxta_test_range();
    cxta_test_rolling();
    cxta_test_cross();
    cxta_test_candles();
    cxta_test_patterns();
    cxta_test_fib();
    cxta_test_wedge();
    cxta_test_tf();
    cxta_test_bar();
    cxta_test_window();
    cxta_test_args();
    cxta_test_pivot();
    cxta_test_pivot_points();
    cxta_test_bos();
    cxta_test_fvg();
    cxta_test_order_block();
    cxta_test_liquidity();
    cxta_test_sfp();
    cxta_test_indicator_vwap();
    cxta_test_structure_wedge();
    cxta_test_sma();
    cxta_test_ema();
    cxta_test_atr();
    cxta_test_rsi();
    cxta_test_macd();
    cxta_test_bollinger();
    cxta_test_adx();
    cxta_test_supertrend();
    cxta_test_donchian();
    cxta_test_keltner();
    cxta_test_price_channel();
    cxta_test_volume_sma();
    cxta_test_wma();
    cxta_test_dema();
    cxta_test_tema();
    cxta_test_hma();
    cxta_test_roc();
    cxta_test_linreg();
    cxta_test_stddev();
    cxta_test_hvol();
    cxta_test_rvol();
    cxta_test_truerange();
    cxta_test_typical();
    cxta_test_median();
    cxta_test_wclose();
    cxta_test_obv();
    cxta_test_zscore();
    cxta_test_extrema();
    cxta_test_ao();
    cxta_test_bop();
    cxta_test_eom();
    cxta_test_volume_ema();
    cxta_test_rma();
    cxta_test_aroon();
    cxta_test_williamsr();
    cxta_test_cci();
    cxta_test_mfi();
    cxta_test_cmf();
    cxta_test_chaikin();
    cxta_test_dpo();
    cxta_test_cmo();
    cxta_test_ppo();
    cxta_test_pvo();
    cxta_test_trix();
    cxta_test_tsi();
    cxta_test_kst();
    cxta_test_mass_index();
    cxta_test_efi();
    cxta_test_nvi();
    cxta_test_stochastic();
    cxta_test_stochrsi();
    cxta_test_mama();
    cxta_test_kama();
    cxta_test_frama();
    cxta_test_vidya();
    cxta_test_fisher();
    cxta_test_connors_rsi();
    cxta_test_coppock();
    cxta_test_schaff();
    cxta_test_choppiness();
    cxta_test_ulcer();
    cxta_test_rvi();
    cxta_test_vwap();
    cxta_test_vortex();
    cxta_test_dominant_cycle();
    cxta_test_ichimoku();
    cxta_test_psar();
    cxta_test_ttm_squeeze();
    cxta_test_trendline();
    cxta_test_volume_profile();
    cxta_test_zigzag();
    cxta_test_divergence();
    cxta_test_anchored_vwap();
    cxta_test_descriptor();
    printf("cxta.test: all tests passed\n");
    return 0;
}
