/**
 * @file cxta.h
 * @brief Umbrella include for cxta.
 */

#pragma once

#include "math/math.h"                  // IWYU pragma: export
#include "signals/signals.h"            // IWYU pragma: export
#include "ts/smoothing.h"               // IWYU pragma: export
#include "ts/range.h"                   // IWYU pragma: export
#include "ts/rolling.h"                 // IWYU pragma: export
#include "ts/cross.h"                   // IWYU pragma: export
#include "ts/pair.h"                    // IWYU pragma: export
#include "ts/candles.h"                 // IWYU pragma: export
#include "ts/patterns.h"                // IWYU pragma: export
#include "ts/fib.h"                     // IWYU pragma: export
#include "ts/wedge.h"                   // IWYU pragma: export
#include "series/bar.h"                 // IWYU pragma: export
#include "series/window.h"              // IWYU pragma: export
#include "series/args.h"                // IWYU pragma: export
#include "structure/pivot.h"            // IWYU pragma: export
#include "structure/pivot_points.h"     // IWYU pragma: export
#include "structure/structure.h"        // IWYU pragma: export
#include "structure/bos.h"              // IWYU pragma: export
#include "structure/fvg.h"              // IWYU pragma: export
#include "structure/order_block.h"      // IWYU pragma: export
#include "structure/liquidity.h"        // IWYU pragma: export
#include "structure/sfp.h"              // IWYU pragma: export
#include "structure/vwap.h"             // IWYU pragma: export
#include "structure/wedge.h"            // IWYU pragma: export
#include "indicators/descriptor.h"      // IWYU pragma: export
#include "indicators/sma.h"             // IWYU pragma: export
#include "indicators/ema.h"             // IWYU pragma: export
#include "indicators/atr.h"             // IWYU pragma: export
#include "indicators/rsi.h"             // IWYU pragma: export
#include "indicators/macd.h"            // IWYU pragma: export
#include "indicators/bollinger.h"       // IWYU pragma: export
#include "indicators/adx.h"             // IWYU pragma: export
#include "indicators/supertrend.h"      // IWYU pragma: export
#include "indicators/donchian.h"        // IWYU pragma: export
#include "indicators/keltner.h"         // IWYU pragma: export
#include "indicators/price_channel.h"   // IWYU pragma: export
#include "indicators/volume_sma.h"      // IWYU pragma: export
#include "indicators/wma.h"             // IWYU pragma: export
#include "indicators/dema.h"            // IWYU pragma: export
#include "indicators/tema.h"            // IWYU pragma: export
#include "indicators/hma.h"             // IWYU pragma: export
#include "indicators/roc.h"             // IWYU pragma: export
#include "indicators/linreg.h"          // IWYU pragma: export
#include "indicators/stddev.h"          // IWYU pragma: export
#include "indicators/hvol.h"            // IWYU pragma: export
#include "indicators/rvol.h"            // IWYU pragma: export
#include "indicators/truerange.h"       // IWYU pragma: export
#include "indicators/typical.h"         // IWYU pragma: export
#include "indicators/median.h"          // IWYU pragma: export
#include "indicators/wclose.h"          // IWYU pragma: export
#include "indicators/obv.h"             // IWYU pragma: export
#include "indicators/zscore.h"          // IWYU pragma: export
#include "indicators/extrema.h"         // IWYU pragma: export
#include "indicators/ao.h"              // IWYU pragma: export
#include "indicators/bop.h"             // IWYU pragma: export
#include "indicators/eom.h"             // IWYU pragma: export
#include "indicators/volume_ema.h"      // IWYU pragma: export
#include "indicators/rma.h"             // IWYU pragma: export
#include "indicators/aroon.h"           // IWYU pragma: export
#include "indicators/williamsr.h"       // IWYU pragma: export
#include "indicators/cci.h"             // IWYU pragma: export
#include "indicators/mfi.h"             // IWYU pragma: export
#include "indicators/cmf.h"             // IWYU pragma: export
#include "indicators/chaikin.h"         // IWYU pragma: export
#include "indicators/dpo.h"             // IWYU pragma: export
#include "indicators/cmo.h"             // IWYU pragma: export
#include "indicators/ppo.h"             // IWYU pragma: export
#include "indicators/pvo.h"             // IWYU pragma: export
#include "indicators/trix.h"            // IWYU pragma: export
#include "indicators/tsi.h"             // IWYU pragma: export
#include "indicators/kst.h"             // IWYU pragma: export
#include "indicators/mass_index.h"      // IWYU pragma: export
#include "indicators/efi.h"             // IWYU pragma: export
#include "indicators/nvi.h"             // IWYU pragma: export
#include "indicators/stochastic.h"      // IWYU pragma: export
#include "indicators/stochrsi.h"        // IWYU pragma: export
#include "indicators/mama.h"            // IWYU pragma: export
#include "indicators/kama.h"            // IWYU pragma: export
#include "indicators/frama.h"           // IWYU pragma: export
#include "indicators/vidya.h"           // IWYU pragma: export
#include "indicators/fisher.h"          // IWYU pragma: export
#include "indicators/connors_rsi.h"     // IWYU pragma: export
#include "indicators/coppock.h"         // IWYU pragma: export
#include "indicators/schaff.h"          // IWYU pragma: export
#include "indicators/choppiness.h"      // IWYU pragma: export
#include "indicators/ulcer.h"           // IWYU pragma: export
#include "indicators/rvi.h"             // IWYU pragma: export
#include "indicators/vwap.h"            // IWYU pragma: export
#include "indicators/vortex.h"          // IWYU pragma: export
#include "indicators/dominant_cycle.h"  // IWYU pragma: export
#include "indicators/ichimoku.h"        // IWYU pragma: export
#include "indicators/psar.h"            // IWYU pragma: export
#include "indicators/ttm_squeeze.h"     // IWYU pragma: export
#include "indicators/trendline.h"       // IWYU pragma: export
#include "indicators/volume_profile.h"  // IWYU pragma: export
#include "indicators/zigzag.h"          // IWYU pragma: export
#include "indicators/fair_value_gap.h"  // IWYU pragma: export
#include "indicators/divergence.h"      // IWYU pragma: export
#include "indicators/anchored_vwap.h"   // IWYU pragma: export
